spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    #url: jdbc:mysql://localhost:3306/matjipdaehak
    #driverClassName: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: smtp.gmail.com
    port: 587
    username: 3moneey
    password: moneymakesmoney99!
    properties.mail.smtp:
      auth: true
      starttls.enabled: true

# mail 설정

