spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    #url: jdbc:mysql://localhost:3306/matjipdaehak
    #driverClassName: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
