spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    #url: jdbc:mysql://localhost:3306/matjipdaehak
    #driverClassName: com.mysql.cj.jdbc.Driver
  sql:
    init:
      data-locations: classpath:colleges.sql, classpath:places.sql, classpath:users.sql, classpath:reviews.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  mail:
    host: smtp.gmail.com
    port: 587
    username: matjipdaehak@gmail.com
    password: aorylgrgglpiymio
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
# mail 설정

